### ISSUE TITLE
White/Transparent text error in output PDF

### ISSUE THREAD

**Issue by graux** [signintech/gopdf#183] opened 2021-07-08 10:50 UTC
Currently I am generating reports in a table format.
It has been working fine for months, but suddenly I have a report for June where all the text is invisible. 
The text is all there, I can extract it using a tool such as pdftotext, but it is invisble when I open the PDF with any pdf viewer or pdf tool such as Scribus.
For instance, the report of May generates a 16 pages PDF with no problems.
Same code, for the June report, generates a 11 pages PDF with invisible text.

I cannot share the PDF as it contains sensible information, but here is an screenshot:
![image](https://user-images.githubusercontent.com/2606751/124909757-20785e00-dfeb-11eb-8979-76cd31f6c2e4.png)

Any idea how to solve this?
Thank you

**Comment by oneplus1000** [comment] 2021-07-08 15:08
Can you give me more information? Maybe a sample code?

**Additional information** if i remember correctly, The code that makes the text transparent in GOPDF is as shown in the figure.
![Screen Shot 2564-07-08 at 22 01 38](https://user-images.githubusercontent.com/1155104/124945741-a373d580-e038-11eb-94a5-22b9bc8013c8.png)

**Comment by s-agena** [comment] 2021-07-09 06:18
Hello!

I came across a similar phenomenon.
Upon investigation, characters that the font did not cover were used.

I was curious that the charCodeToGlyphIndexFormat4 function did not return an error.

Thank you

**Comment by graux** [comment] 2021-07-09 08:08
Hi there, 
this is the code that generates that part of the table:
```
	for rowIndex, row := range allRows {
		isFooter = false
		if rowIndex >= len(sheetData.Rows) {
			pdf.SetFillColor(243, 243, 243)
			pdf.RectFromUpperLeftWithStyle(offsetX, offsetY, docInnerWidth, cellHeight, "F")
			pdf.SetTextColor(102, 102, 102)
			isFooter = true
		} else if rowIndex%2 != 0 && row[0] != xlsx.SheetCellDivider {
			pdf.SetFillColor(250, 250, 250)
			pdf.RectFromUpperLeftWithStyle(offsetX, offsetY, docInnerWidth, cellHeight, "F")
		}
		if row[0] == xlsx.SheetCellDivider {
			pdf.SetFillColor(kolorTeal.R, kolorTeal.G, kolorTeal.B)
			pdf.RectFromUpperLeftWithStyle(offsetX, offsetY+cellHeight/3, docInnerWidth, cellHeight/3, "F")
		} else {
			for colIndex, cellVal := range row {
				rowCol = sheetData.Columns[colIndex]
				if rowCol.Show != nil && !*rowCol.Show {
					continue
				}
				currentFontSize = int(fontSize)
				if rowCol.Format == xlsx.FormatTextSmall || rowCol.Format == xlsx.FormatDateShortSmall || rowCol.Format == xlsx.FormatDateSmall {
					currentFontSize = fontSizeSmall
					fontSizeOffsetY = 2.0
				} else if rowCol.Format == xlsx.FormatTextTiny {
					currentFontSize = fontSizeTiny
					fontSizeOffsetY = 4.0
				} else {
					fontSizeOffsetY = 0.0
				}
				_ = pdf.SetFont("Lato", "", currentFontSize)
				cellWidth = rowCol.Width
				cellInnerWidth = cellWidth - (cellHPadding * 2)
				cellText = GetTableColText(cellVal, rowCol.Format, currencySymbol, langCode, utcOffset)
				textWidth, _ = pdf.MeasureTextWidth(cellText)
				for textWidth > cellInnerWidth {
					cellText = strings.Trim(cellText, "…")
					cellText = cellText[0:len(cellText)-1] + "…"
					textWidth, _ = pdf.MeasureTextWidth(cellText)
				}
				if rowCol.AlignRight || isFooter {
					pdf.SetX((offsetX + cellWidth) - (cellHPadding + textWidth))
				} else {
					pdf.SetX(offsetX + cellHPadding)
				}
				if rowCol.Format == xlsx.FormatCurrency && rowCol.IsTotal {
					if cellFloat, ok := cellVal.(float64); ok {
						total += cellFloat
					} else if cellFloat, ok := cellVal.(float32); ok {
						total += float64(cellFloat)
					}
				}
				pdf.SetY(offsetY + cellVPadding + fontSizeOffsetY)
				_ = pdf.Cell(nil, cellText)
				offsetX += cellWidth
			}
		}
		offsetY += cellHeight
		offsetX = 40
		if offsetY > pageLimit {
			pdf.SetLineWidth(0.6)
			pdf.SetStrokeColor(219, 219, 219)
			pdf.Line(offsetX, offsetY, offsetX+docInnerWidth, offsetY)
			addPage(iConf, pdf)
			offsetY = 40
		}
	}
```
The first two conditions fill the rows with alternating colors.
The third one is to print table dividers (I use this to visually split the rows between days).
The last section is the one that prints the cell values which are not shown in that report. This is the first time that has happened in over 2 years. I've tried different releases and did not change, it always generates blank.

Yesterday I tried to delete some rows and find if there was some content that was breaking the PDF. But I could not find a specific set of data that caused the issue. It happened when a bunch of rows were printed out, but I tried to test separate combinations to narrow it down, but I could not.

Let me know if there is anything else I can do from my end.
Thanks

**Comment by s-agena** [comment] 2021-07-09 08:28
In my case, when I parsed the pdf on the following site, I found that this was the cause because there was an unfamiliar character type.

https://products.aspose.app/pdf/parser

Thank you

**Comment by graux** [comment] 2021-07-09 10:18
s-agena thanks for the feedback.
I have tried the parser and it did parse the PDF correctly, the text exported is readable and there are no errors/warnings about characters or anything.
So I believe we have encountered different problems.

**Comment by oneplus1000** [comment] 2021-07-09 13:50
What happens if you remove function SetFillColor() and RectFromUpperLeftWithStyle ()?

**Comment by graux** [comment] 2021-07-09 15:25
@oneplus1000 I have already tried, but the output is the same (without alternating colors)
I have tried to comment out everything but the internal loop of the columns, and simplifying the code, no changes.
I have tried to add a Rect for every cell too, it did not work either.

**Comment by s-agena** [comment] 2021-07-12 05:43
I wrote a reproduction code.
Please write the following code in gopdf_test.go and execute it.

Changing the Japanese hiragana to one character will give different results.
"あい"→"い"

// err = pdf.CellWithOption(&rect, "あい", op)
err = pdf.CellWithOption(&rect, "あ", op)
-------
func TestWhiteTransparent(t *testing.T) {
	err := initTesting()
	if err != nil {
		t.Error(err)
		return
	}
	// create pdf.
	pdf := GoPdf{}
	pdf.Start(Config{PageSize: *PageSizeA4})
	pdf.AddPage()
	err = pdf.AddTTFFont("LiberationSerif-Regular", "test/res/LiberationSerif-Regular.ttf")
	if err != nil {
		t.Error(err)
		return
	}
	err = pdf.SetFont("LiberationSerif-Regular", "", 14)
	if err != nil {
		t.Error(err)
		return
	}
	// write text.
	op := CellOption{Align: Left | Middle}
	rect := Rect{W: 20, H: 30}
	pdf.SetX(350)
	pdf.SetY(50)
	err = pdf.CellWithOption(&rect, "あい", op)
	if err != nil {
		t.Error(err)
		return
	}
	pdf.SetY(100)
	err = pdf.CellWithOption(&rect, "abcdef.", op)
	if err != nil {
		t.Error(err)
		return
	}
	pdf.WritePdf("./test/out/white_transparent.pdf")
}

**Comment by oneplus1000** [comment] 2021-07-12 17:10
Thanks you @s-agena  for the reproduction code. I think I have solved the problem (in the reproduction code). I pushed the code to the branch "issue_183". I would like to ask you to help me. test it, thanks you.

**Comment by s-agena** [comment] 2021-07-13 00:00
Hi.

**Comment by graux** [comment] 2021-07-14 09:57
Great job @oneplus1000 & @s-agena.
This fixes my report and all the text is now visible using that commit.
@oneplus1000, should I close the issue?
Thank you!

**Comment by oneplus1000** [comment] 2021-07-15 03:36
@s-agena  I'll close this issue myself after I've done a few tests (and merge), probably on Saturday or Sunday.

**Comment by oneplus1000** [comment] 2021-07-17 03:16
> Hi.
> 
> I checked the output result with issue_183 applied. I have no problem.
> How about @graux?
> Depending on the application, it may be necessary to additionally describe the process of appropriately selecting the font to be used for each cell.
> 
> (I want a helper function that determines if a cell can be displayed in the selected font without any problem.)
> 
> Thank you

I have added the func OnGlyphNotFound to gopdf.TtfOption{}
It is called whenever gopdf can't find that glyph inside the ttf file. (I did this because I don't want to return an error as it might break the old code.)
*You can see an example at file gopdf_test.go function Test WhiteTransparent.

![Screen Shot 2564-07-17 at 10 08 00](https://user-images.githubusercontent.com/1155104/126023758-698a198b-b725-4d51-927c-873ba2cc0a19.png)

**Comment by oneplus1000** [comment] 2021-07-17 03:21
The code is already in the master, so I closed this issue.
thank you. @graux @s-agena

**Closed by oneplus1000** 2021-07-17 03:21 UTC

**Comment by akhll** [comment] 2021-08-31 14:11
@oneplus1000 
i found one case. 
Font Symbola has a symbol with unicode U+000A (https://www.fileformat.info/info/unicode/font/symbola/list.htm), but i am getting a error "glyph not found".

**Comment by akhll** [comment] 2021-08-31 14:20
i have checked another fonts, and i get "glyph not found" error with any another fonts.

**Comment by akhll** [comment] 2021-08-31 15:12
the same with U+000D symbol https://www.fileformat.info/info/unicode/char/000d/index.htm

**Comment by akhll** [comment] 2021-09-06 08:28
@oneplus1000 look please

**Comment by oneplus1000** [comment] 2021-09-06 14:06
I think because those unicodes are control characters. I think control characters don't have glyphs.
U+000A is End of Line
U+000D is Carriage Return

**Comment by akhll** [comment] 2021-09-06 14:46
yeah, you right, i have not thought about it. 
thank you
